stages:
  - test
  - build

check:
  stage: test
  only:
  - master
  - deploy
  image: hshnwinps/dev
  script:
  - pipenv install --dev
  - pipenv run python proctor.py -v full-check
  - pipenv run tox -e 37

build:
  stage: build
  only:
  - deploy
  image: hshnwinps/dev
  script:
  - pipenv install --dev
  - pipenv run ./scripts/build_image.sh
