stages:
  - test
  - build

check:
  stage: test
  image: hshnwinps/dev
  script:
  - pipenv install --dev
  - pipenv run ./scripts/check.sh
  - pipenv run ./scripts/coverage.sh

build:
  stage: build
  image: hshnwinps/dev
  only:
  - deploy
  script:
  - ./scripts/run_dev.sh build runner "" ""
