stages:
  - source
  - test
  - build

check:
  stage: source
  only:
  - master
  - deploy
  - release
  image: hshnwinps/pydev
  script:
  - pipenv install --dev
  - pipenv run python make.py -v full-check

test:
  stage: test
  only:
  - deploy
  - release
  image: hshnwinps/pydev
  script:
  - pipenv install --dev
  - pipenv run tox -e py37

build:
  stage: build
  only:
  - deploy
  image: hshnwinps/pydev
  script:
  - docker build -t grpy .
